### PR TITLE
Added support for SocketCluster https options

### PR DESCRIPTION
**Pull request by jozanza**
Added the following cli flags:

```
--protocol   [protocol="http"]
--key        [protocolOptions.key]
--cert       [protcolOptions.cert]
--passphrase [protcolOptions.passphrase]
```

Example Usage:

``` bash
remotedev --protocol=https --key="$(< ./path/to/key.pem)" --cert="$(< ./path/to/cert.pem)" --passphrase=foo
```

### CODE REVIEW

**Comment by jozanza** [comment]
This is for #8 btw

**Comment by zalmoxisus** [comment]
Thanks a lot! Do we also need to add `secure: true` in `remote-redux-devtools`? Or you use it for something else?

**Comment by jozanza** [comment]
I don't think `remote-redux-devtools` needs any changes.
 [remotedev-app](https://github.com/zalmoxisus/remotedev-app), on the other hand, will need some kind of update to add "Use HTTPS" switch in the settings modal. Want me to take a stab at it?

**Comment by jozanza** [comment]
I don't think `remote-redux-devtools` needs any changes.
`remotedev-app`, on the other hand, will need some kind of update to add "Use HTTPS" switch in the settings modal. Does that sound correct to you?

**Comment by jozanza** [comment]
Oh and can we bump the version and publish to npm for this PR merge?

**Comment by zalmoxisus** [comment]
OK, published to npm.

I think both of them need to provide `secure: true`, otherwise they will use WS not WSS.

**Comment by jozanza** [comment]
Awesome. I can work on updating both projects later tonight if you'd like.

**Comment by zalmoxisus** [comment]
@jozanza, it would be welcome. Thanks for the contribution!

**Comment by jhen0409** [comment]
> `--key="$(< ./path/to/key.pem)" --cert="$(< ./path/to/cert.pem)"`

Maybe we should use `fs.readFileSync(path.resolve(process.cwd(), filePath), 'utf-8')` instead? I think this usage is not very perfect.

Also, I send a PR #10.

**Comment by zalmoxisus** [comment]
Yes, it looks better, though it is a breaking change for those who started to use the current approach.

@jozanza what do you think?

**Comment by jozanza** [comment]
@zalmoxisus sounds good to me. I don't mind migrating :)

**Pull request merged**
