### PR TITLE
Include remotedev-app

### PR DESCRIPTION
**Pull request by jhen0409**
Include simple remotedev-app to server index page, it load bundles from [npmcdn.com](https://npmcdn.com).

related #4.

### CODE REVIEW

**Comment by zalmoxisus** [comment]
@jhen0409, why not just use all this directly from `remotedev-app`, e.g. to add `web` build to the npm package?

**Comment by zalmoxisus** [comment]
zIndex was added to `redux-slider-monitor` just now? Because in the previous version weren't any problems with styles: `view-source:http://remotedev.io/`

**Comment by jhen0409** [comment]
> zIndex was added to redux-slider-monitor just now? Because in the previous version weren't any problems with styles: view-source:http://remotedev.io/

It will be the following problem:


However, it should be able to solve in remotedev-app.

**Comment by jhen0409** [comment]
> why not just use all this directly from remotedev-app, e.g. to add web build to the npm package?

The `build/web` will cannot set default options.

**Comment by jhen0409** [comment]
I will send another PR for `Return socketcluster server for export function`.

**Comment by zalmoxisus** [comment]
I see. Thanks for clarifications! I will fix zIndex in `remotedev-app` in another way.

About setting default port, are there any downsides if we include it in the generated `build/web`? It will not be included in development, so will not cause problems while running with webpack's server, and will not spoil `remotedev.io` as the `location.port` is empty there (we should take it into consideration).

**Comment by jhen0409** [comment]
> will not spoil remotedev.io as the location.port is empty there (we should take it into consideration).

Maybe we should render `worker.scServer.sourcePort`?

**Comment by zalmoxisus** [comment]
The intent was to just use here the bundle from `remotedev-app`, so it is not possible to pass `worker.scServer.sourcePort` in this scenario (or is it?).

I do not see any problems to implement what I described directly in `remotedev-app` for the web bundle. So [here](https://github.com/zalmoxisus/remotedev-app/blob/master/src/web/index.js) we check if NODE_ENV is production and `location.port` isn't empty (not from `remotedev.io`). If so, we can include `location.host` and port as props. Or are any drawbacks?

**Comment by jhen0409** [comment]
I mean we can render `worker.scServer.sourcePort` to `index` from remotedev-server, it will replace `location.port`. But you want to be all resolved in `build/web`? I think it's no problem.

**Comment by zalmoxisus** [comment]
How do you intend to pass `worker.scServer.sourcePort` to the frontend's script?

**Comment by jhen0409** [comment]
Like the above commit, but it should be render `worker.options.port`, then the `build/web` need to accept `window.remotedevOptions`.

**Comment by zalmoxisus** [comment]
Sorry for keeping it so long. I was planning to delegate this to remotedev-app, but on the other thought we want to have there an electron app running the server, so we get stuck into dependencies. That said, you solution is best to be implemented here. Thanks a lot for the contribution and sorry again for the delay!

**Pull request merged**
