### PR TITLE
Render views no mater what the cwd is

### PR DESCRIPTION
**Pull request by nevir**

### CODE REVIEW

**Comment by zalmoxisus** [comment]
Thanks a lot for the contribution. Could you please give more details about the problem and the solution? I thought we already include `index.ejs`, not?

**Comment by nevir** [comment]
Sorry, when running `remotedev` as a standalone binary, if I `GET /` on it, it will throw an exception like:

`Error: Failed to lookup view "index" in views directory "<whatever my CWD is>/views"`

Express looks in `<CWD>/views` by default

**Comment by zalmoxisus** [comment]
I see. Thanks!

**Comment by jhen0409** [comment]
Sorry, my bad, I ignored it at that time. :(

**Comment by zalmoxisus** [comment]
Thanks, guys! Released in `0.0.5`.

**Pull request merged**
